# Author: Louis OLLIVIER (louis.xiv.bis@gmail.com)
# Date : Feb 2025

configfile: "config/config.yaml"
conda: "workflow/envs/environment.yaml"

# Load the predefined resource requirments ("config/resources.yaml")
import yaml
with open("config/resources.yaml", "r") as f:
    resources = yaml.safe_load(f)

SAMPLES = config["samples"]
VCF = config["vcf"]

localrules:
    all,

rule all:
    input:       
        expand("results/ABR_gz/{sample}_ABR.tsv.gz", sample=SAMPLES),
        expand("results/hist_ABR/{sample}_ABR_filtered_hist.png", sample=SAMPLES),
        expand("results/ABR_filtered_binned/{sample}_ABR_filtered_binned.csv", sample=SAMPLES),
        "results/merged_filtered_binned_ABR.csv",
        # "results/ploidy_strain.csv",


include: "rules/get_DP_AD.smk"
include: "rules/compute_ABR.smk"
include: "rules/zip_ABR.smk"
include: "rules/filter_ABR.smk"
include: "rules/hist_plot_ABR.smk"
include: "rules/bin_ABR.smk"
include: "rules/merge_ABR.smk"
# include: "rules/predict_ploidy.smk"