# Author: Louis OLLIVIER (louis.xiv.bis@gmail.com)
# Date : Feb 2025

configfile: "config/config.yaml"
conda: "workflow/envs/environment.yaml"

# Load the predefined resource requirments ("config/resources.yaml")
import yaml
with open("config/resources.yaml", "r") as f:
    resources = yaml.safe_load(f)

SAMPLES = config["samples"]
VCF = config["vcf"]

localrules:
    all,

rule all:
    input:       
        expand("results/DP_AD_gz/{sample}_DP_AD.txt.gz", sample=SAMPLES),
        expand("results/violin_plot_ABR/{sample}_ABR_filtered_violinPlot.png", sample=SAMPLES),
        expand("results/ABR_filtered_binned/{sample}_ABR_filtered_binned.csv", sample=SAMPLES),

include: "rules/get_DP_AD.smk"
include: "rules/zip_DP_AD.smk"
include: "rules/compute_ABR.smk"
include: "rules/filter_ABR.smk"
include: "rules/violin_plot_ABR.smk"
include: "rules/bin_ABR.smk"
include: "rules/merge_ABR_csv.smk"