vcf: '/shared/projects/yeast_neutral_model/analysis_vcf/data/toy_200samples.vcf.gz'
# vcf: '/shared/projects/yeast_neutral_model/analysis_vcf/data/LDpruned_toy_200samples.vcf.gz'

samples: 
  - PD35A
  - DBVPG1029
  - HN2.2
  - B1S50
  - BE034
  - AWRI935
  - F10-S101
  - CLIB655
  - GS105
  - AWRI1017
  - DBVPG6694
  - MTJZ3
  - HN10
  - SX6-2
  - NCYC360
  - OCP176
  - BE063
  - HB-C-TUKITUKI2-4
  - NCYC1289
  - WI010
  - L-1374
  - SAN32
  - BQ1.1
  - NCYC1102
  - CLIB561
  - P44-ES122
  - NCYC3077
  - RG11
  - NIGF4
  - NCYC88
  - H348-7
  - GZU1
  - H1S129
  - A.Nottingham
  - ANG.CJ.1
  - CLQCA-09-001
  - AWRI1727
  - YJM965
  - 21-4-0122
  - SCN6
  - B68019c
  - YJM269-2
  - NCYC3445
  - B4-S41
  - AWRI266
  - TUM-211
  - NSECHsf-F2
  - NCYC1413
  - AWRI724
  - B9c-1
  - NCYC2779
  - YJM1118
  - BE009
  - HZJZ4.5
  - HNN1
  - Y9
  - OCP279
  - X2180-1A
  - YJM1122
  - WLP550
  - N-1S78
  - 22A4
  - YPS606
  - T.52-3C
  - DBVPG4902
  - AWRI1796
  - SAN22
  - NCYC1408
  - IT-CXU-S19
  - SAF2
  - C-6
  - Y264
  - Lib54
  - CBS4079
  - CLI-25
  - NCYC621
  - SBV017
  - FJ2
  - AQ2717
  - CBS9563-2
  - YM3.1
  - T78
  - AWRI1077
  - Y1
  - DBVPG6350
  - BE030
  - yHKS338
  - yHQL612
  - CLIB227
  - JM4.8
  - YO820
  - CBS2805
  - YJM560
  - MARLIsf-C1
  - S13
  - BJ10-2
  - OS-1326
  - AQ2722
  - PD10A
  - CH13
  - NPA06.1
  - CCY-21-4-97
  - MTF2417
  - CBS1230
  - PB67
  - UWOPS03-429.1
  - NCYC479
  - NSERVsf-H8
  - AWRI1784
  - OCP041
  - CBS6333
  - CLIB631
  - IT-DDR-S21
  - C7-S21
  - CEN.PK2-1Ca
  - K1-1
  - P68-H3-S63
  - CH06
  - ZP650
  - CBS1398
  - T.52-3A
  - YMD1868
  - OS-1462
  - A-19
  - BE077
  - PB11
  - PYR4e
  - 2-155
  - WL005
  - WL015
  - A-9-S4
  - ANGGW.1
  - L712
  - CLQCA-10-003
  - SAN11
  - YJM963
  - DBVPG1564
  - NCYC1765
  - DBS11
  - A9-S122
  - C10-S61
  - AG015
  - CBS1388a
  - MTF2548
  - YJM413-b
  - HTHMAsf-H11
  - ZP565
  - MTF2397
  - A.1945
  - YJM1115
  - G4-S107
  - Y644
  - S7
  - CBS1252
  - DBVPG6695
  - SM69s1
  - WI007
  - EXF-5046
  - AWRI939
  - Y3
  - P24-H3-S38
  - MTJZ2
  - WA-WaitakereRd-4
  - WLP800
  - ZP785
  - WI-S-OAKURA-4
  - WSEHOsf-D1
  - NCYC3036
  - yHAB39
  - NCYC1111
  - FTPW35
  - MTKSKsf-E2
  - Y9-4
  - B-17
  - JSN4
  - SP010
  - CLIB651
  - Muntons
  - IT-DED-S33
  - HLJ201
  - ZP563
  - BE070
  - GEN58f3
  - T52-27
  - W-S121
  - A-9
  - B-7-S10
  - YJM672
  - N493-2C
  - NCYC2855
  - PD34A-2
  - CJM19.6
  - YO466
  - SX8
  - YO707
  - YJM1097
  - SJ7L01
  - VKM-Y-504:S
  - YPS163
  - CLIB1062

# Config used for training dataset

# vcf: '/shared/projects/yeast_neutral_model/1011Matrix.gvcf.gz'

# samples: 
#   - AAA
#   - AAB
#   - AAC
#   - AAD
#   - AAE
#   - AAG
#   - AAH
#   - AAI
#   - AAK
#   - AAL
#   - AAM
#   - AAN
#   - AAP
#   - AAQ
#   - AAR
#   - AAS
#   - AAT
#   - AAV
#   - ABA
#   - ABB
#   - ABC
#   - ABD
#   - ABE
#   - ABF
#   - ABG
#   - ABH
#   - ABI
#   - ABK
#   - ABL
#   - ABM
#   - ABP
#   - ABQ
#   - ABR
#   - ABS
#   - ABT
#   - ABV
#   - ACA
#   - ACB
#   - ACC
#   - ACD
#   - ACF
#   - ACG
#   - ACH
#   - ACI
#   - ACK
#   - ACL
#   - ACM
#   - ACN
#   - ACP
#   - ACQ
#   - ACR
#   - ACS
#   - ACT
#   - ACV
#   - ADA
#   - ADB
#   - ADC
#   - ADD
#   - ADE
#   - ADF
#   - ADG
#   - ADH
#   - ADI
#   - ADK
#   - ADL
#   - ADM
#   - ADN
#   - ADP
#   - ADQ
#   - ADR
#   - ADS
#   - ADT
#   - ADV
#   - AEA
#   - AEB
#   - AEC
#   - AEE
#   - AEF
#   - AEG
#   - AEH
#   - AEI
#   - AEK
#   - AEL
#   - AEM
#   - AEN
#   - AEP
#   - AEQ
#   - AER
#   - AES
#   - AET
#   - AEV
#   - AFA
#   - AFB
#   - AFC
#   - AFD
#   - AFE
#   - AFF
#   - AFG
#   - AFH
#   - AFI
#   - AFK
#   - AFL
#   - AFM
#   - AFN
#   - AFP
#   - AFQ
#   - AFR
#   - AFS
#   - AFT
#   - AFV
#   - AGA
#   - AGB
#   - AGC
#   - AGE
#   - AGF
#   - AGG
#   - AGH
#   - AGI
#   - AGK
#   - AGL
#   - AGM
#   - AGN
#   - AGP
#   - AGR
#   - AGS
#   - AGT
#   - AGV
#   - AHA
#   - AHB
#   - AHC
#   - AHD
#   - AHE
#   - AHF
#   - AHG
#   - AHH
#   - AHI
#   - AHK
#   - AHL
#   - AHM
#   - AHN
#   - AHP
#   - AHQ
#   - AHR
#   - AHS
#   - AHT
#   - AHV
#   - AIA
#   - AIB
#   - AIC
#   - AID
#   - AIE
#   - AIF
#   - AIG
#   - AII
#   - AIK
#   - AIL
#   - AIM
#   - AIN
#   - AIP
#   - AIQ
#   - AIR
#   - AIT
#   - AKB
#   - AKC
#   - AKD
#   - AKE
#   - AKG
#   - AKH
#   - AKI
#   - AKL
#   - AKM
#   - AKN
#   - AKP
#   - AKQ
#   - AKR
#   - AKS
#   - AKT
#   - AKV
#   - ALA
#   - ALB
#   - ALC
#   - ALD
#   - ALE
#   - ALG
#   - ALH
#   - ALI
#   - ALK
#   - ALL
#   - ALM
#   - ALN
#   - ALP
#   - ALQ
#   - ALR
#   - ALS
#   - ALT
#   - ALV
#   - AMA
#   - AMB
#   - AMC
#   - AMD
#   - AMF
#   - AMG
#   - AMH
#   - AMI
#   - AMK
#   - AML
#   - AMM
#   - AMN
#   - AMP
#   - AMQ
#   - AMR
#   - AMS
#   - AMT
#   - ANA
#   - ANC
#   - AND
#   - ANE
#   - ANF
#   - ANG
#   - ANH
#   - ANI
#   - ANK
#   - ANL
#   - ANM
#   - ANN
#   - ANP
#   - ANQ
#   - ANR
#   - ANS
#   - ANT
#   - ANV
#   - APA
#   - APC
#   - APD
#   - APE
#   - APF
#   - APG
#   - APH
#   - API
#   - APK
#   - APL
#   - APM
#   - APN
#   - APP
#   - APQ
#   - APR
#   - APS
#   - APT
#   - APV
#   - AQA
#   - AQB
#   - AQC
#   - AQD
#   - AQE
#   - AQG
#   - AQH
#   - AQI
#   - AQM
#   - AQN
#   - AQP
#   - AQQ
#   - AQR
#   - AQS
#   - AQT
#   - ARA
#   - ARB
#   - ARC
#   - ARE
#   - ARG
#   - ARH
#   - ARI
#   - ARK
#   - ARL
#   - ARM
#   - ARN
#   - ARP
#   - ARQ
#   - ARR
#   - ARS
#   - ART
#   - ARV
#   - ASA
#   - ASB
#   - ASC
#   - ASD
#   - ASE
#   - ASG
#   - ASH
#   - ASL
#   - ASM
#   - ASN
#   - ASP
#   - ASR
#   - ASS
#   - AST
#   - ASV
#   - ATA
#   - ATB
#   - ATC
#   - ATD
#   - ATE
#   - ATH
#   - ATM
#   - ATN
#   - ATP
#   - ATQ
#   - ATR
#   - ATS
#   - ATV
#   - AVB
#   - AVC
#   - AVD
#   - AVH
#   - AVI
#   - AVK
#   - AVL
#   - AVM
#   - AVN
#   - AVP
#   - AVQ
#   - AVR
#   - AVS
#   - AVT
#   - AVV
#   - BAA
#   - BAB
#   - BAC
#   - BAD
#   - BAE
#   - BAF
#   - BAG
#   - BAH
#   - BAI
#   - BAK
#   - BAL
#   - BAM
#   - BAN
#   - BAP
#   - BAQ
#   - BAR
#   - BAS
#   - BAT
#   - BAV
#   - BBA
#   - BBB
#   - BBC
#   - BBD
#   - BBE
#   - BBF
#   - BBG
#   - BBH
#   - BBI
#   - BBK
#   - BBL
#   - BBM
#   - BBP
#   - BBQ
#   - BBR
#   - BBS
#   - BBT
#   - BBV
#   - BCA
#   - BCB
#   - BCC
#   - BCD
#   - BCE
#   - BCF
#   - BCG
#   - BCH
#   - BCI
#   - BCK
#   - BCL
#   - BCM
#   - BCN
#   - BCP
#   - BCQ
#   - BCR
#   - BCS
#   - BCT
#   - BCV
#   - BDA
#   - BDB
#   - BDC
#   - BDD
#   - BDE
#   - BDF
#   - BDG
#   - BDH
#   - BDI
#   - BDK
#   - BDL
#   - BDM
#   - BDN
#   - BDP
#   - BDQ
#   - BDR
#   - BDS
#   - BDT
#   - BDV
#   - BEA
#   - BEB
#   - BEC
#   - BED
#   - BEE
#   - BEF
#   - BEG
#   - BEH
#   - BEI
#   - BEK
#   - BEM
#   - BEN
#   - BEP
#   - BEQ
#   - BER
#   - BES
#   - BET
#   - BEV
#   - BFA
#   - BFB
#   - BFC
#   - BFD
#   - BFE
#   - BFG
#   - BFH
#   - BFK
#   - BFL
#   - BFM
#   - BFN
#   - BFP
#   - BFQ
#   - BFR
#   - BFS
#   - BFT
#   - BFV
#   - BGA
#   - BGB
#   - BGC
#   - BGD
#   - BGE
#   - BGF
#   - BGG
#   - BGH
#   - BGI
#   - BGK
#   - BGL
#   - BGM
#   - BGN
#   - BGP
#   - BGQ
#   - BGR
#   - BGS
#   - BGT
#   - BGV
#   - BHA
#   - BHB
#   - BHC
#   - BHD
#   - BHE
#   - BHF
#   - BHG
#   - BHH
#   - BHI
#   - BHK
#   - BHL
#   - BHM
#   - BHN
#   - BHP
#   - BHQ
#   - BHR
#   - BHS
#   - BHT
#   - BHV
#   - BIA
#   - BIB
#   - BIC
#   - BID
#   - BIE
#   - BIF
#   - BIG
#   - BIH
#   - BII
#   - BIK
#   - BIL
#   - BIM
#   - BIN
#   - BIP
#   - BIQ
#   - BIR
#   - BIS
#   - BIT
#   - BKA
#   - BKC
#   - BKD
#   - BKE
#   - BKF
#   - BKG
#   - BKH
#   - BKI
#   - BKK
#   - BKL
#   - BKM
#   - BKN
#   - BKP
#   - BKQ
#   - BKR
#   - BKS
#   - BKT
#   - BLA
#   - BLB
#   - BLC
#   - BLD
#   - BLE
#   - BLF
#   - BLG
#   - BLH
#   - BLI
#   - BLK
#   - BLL
#   - BLM
#   - BLN
#   - BLP
#   - BLQ
#   - BLR
#   - BLS
#   - BLT
#   - BLV
#   - BMA
#   - BMB
#   - BMC
#   - BMD
#   - BME
#   - BMF
#   - BMG
#   - BMH
#   - BMI
#   - BMK
#   - BML
#   - BMM
#   - BMN
#   - BMQ
#   - BMR
#   - BMV
#   - BNA
#   - BNB
#   - BNC
#   - BND
#   - BNE
#   - BNF
#   - BNG
#   - BNH
#   - BNI
#   - BNK
#   - BNL
#   - BNM
#   - BNN
#   - BNP
#   - BNQ
#   - BNR
#   - BNT
#   - BNV
#   - BPA
#   - BPB
#   - BPC
#   - BPF
#   - BPG
#   - BPH
#   - BPI
#   - BPK
#   - BPL
#   - BPM
#   - BPN
#   - BPP
#   - BPQ
#   - BPR
#   - BPT
#   - BPV
#   - BQA
#   - BQB
#   - BQC
#   - BQE
#   - BQG
#   - BQH
#   - BQI
#   - BQM
#   - BQN
#   - BQP
#   - BQQ
#   - BQR
#   - BQS
#   - BQT
#   - BRA
#   - BRB
#   - BRC
#   - BRD
#   - BRE
#   - BRF
#   - BRG
#   - BRH
#   - BRK
#   - BRL
#   - BRM
#   - BRP
#   - BRQ
#   - BRV
#   - BSA
#   - BSB
#   - BSC
#   - BSD
#   - BSE
#   - BSG
#   - BSI
#   - BSK
#   - BSL
#   - BSM
#   - BSN
#   - BSP
#   - BSR
#   - BSS
#   - BST
#   - BTA
#   - BTB
#   - BTC
#   - BTD
#   - BTE
#   - BTF
#   - BTG
#   - BTH
#   - BTI
#   - BTL
#   - BTN
#   - BTP
#   - BTR
#   - BTS
#   - BTT
#   - BTV
#   - BVA
#   - BVB
#   - BVC
#   - BVD
#   - BVE
#   - BVF
#   - BVG
#   - BVH
#   - BVK
#   - BVM
#   - BVT
#   - BVV
#   - CAA
#   - CAB
#   - CAC
#   - CAD
#   - CAE
#   - CAF
#   - CAH
#   - CAI
#   - CAK
#   - CAL
#   - CAM
#   - CAN
#   - CAP
#   - CAQ
#   - CAR
#   - CAS
#   - CAT
#   - CAV
#   - CBA
#   - CBB
#   - CBC
#   - CBD
#   - CBE
#   - CBF
#   - CBG
#   - CBH
#   - CBI
#   - CBK
#   - CBL
#   - CBM
#   - CBN
#   - CBR
#   - CCC
#   - CCD
#   - CCE
#   - CCF
#   - CCG
#   - CCH
#   - CCI
#   - CCL
#   - CCM
#   - CCN
#   - CCP
#   - CCQ
#   - CCR
#   - CCS
#   - CCT
#   - CCV
#   - CDA
#   - CDB
#   - CDC
#   - CDD
#   - CDE
#   - CDF
#   - CDG
#   - CDH
#   - CDI
#   - CDK
#   - CDL
#   - CDM
#   - CDN
#   - CDP
#   - CDQ
#   - CDR
#   - CDS
#   - CDT
#   - CDV
#   - CEA
#   - CEB
#   - CEC
#   - CED
#   - CEE
#   - CEF
#   - CEG
#   - CEH
#   - CEI
#   - CEK
#   - CEL
#   - CEM
#   - CEN
#   - CEP
#   - CEQ
#   - CER
#   - CES
#   - CET
#   - CEV
#   - CFA
#   - CFB
#   - CFC
#   - CFD
#   - CFE
#   - CFF
#   - CFG
#   - CFH
#   - CFI
#   - CFM
#   - CFN
#   - CFP
#   - CFQ
#   - CFR
#   - CFS
#   - CFT
#   - CFV
#   - CGB
#   - CGC
#   - CGD
#   - CGE
#   - CGG
#   - CGH
#   - CGI
#   - CGK
#   - CGL
#   - CGN
#   - CGP
#   - CGQ
#   - CGR
#   - CGS
#   - CGT
#   - CGV
#   - CHA
#   - CHB
#   - CHC
#   - CHD
#   - CHE
#   - CHF
#   - CHG
#   - CHH
#   - CHI
#   - CHK
#   - CHL
#   - CHM
#   - CHN
#   - CHP
#   - CHQ
#   - CHR
#   - CHS
#   - CHT
#   - CHV
#   - CIA
#   - CIB
#   - CIC
#   - CID
#   - CIE
#   - CIF
#   - CIG
#   - CIH
#   - CII
#   - CIK
#   - CIL
#   - CIM
#   - CIN
#   - CIP
#   - CIQ
#   - CIR
#   - CIS
#   - CIT
#   - CIV
#   - CKA
#   - CKB
#   - CKC
#   - CKD
#   - CKE
#   - CKF
#   - CKG
#   - CKH
#   - CKI
#   - CKK
#   - CKL
#   - CKM
#   - CKN
#   - CKP
#   - CKQ
#   - CKR
#   - CKS
#   - CKT
#   - CKV
#   - CLA
#   - CLB
#   - CLC
#   - CLD
#   - CLG
#   - CLH
#   - CLI
#   - CLK
#   - CLL
#   - CLM
#   - CLN
#   - CLP
#   - CLQ
#   - CLR
#   - CLS
#   - CLT
#   - CLV
#   - CMB
#   - CMC
#   - CMD
#   - CME
#   - CMF
#   - CMG
#   - CMH
#   - CMI
#   - CMK
#   - CML
#   - CMM
#   - CMN
#   - CMP
#   - CMQ
#   - CMS
#   - CMT
#   - CNB
#   - CNC
#   - CNE
#   - CNF
#   - CNG
#   - CNH
#   - CNI
#   - CNK
#   - CNL
#   - CNM
#   - CNN
#   - CNP
#   - CNQ
#   - CNR
#   - CNS
#   - CNT
#   - CNV
#   - CPA
#   - CPB
#   - CPC
#   - CPD
#   - CPE
#   - CPF
#   - CPG
#   - CPI
#   - CPK
#   - CPL
#   - CPM
#   - CPN
#   - CPQ
#   - CPR
#   - CPS
#   - CPT
#   - CQA
#   - CQB
#   - CQC
#   - CQD
#   - CQE
#   - CQF
#   - CQG
#   - CQH
#   - CQI
#   - CQK
#   - CQL
#   - CQM
#   - CQN
#   - CQP
#   - CQQ
#   - CQR
#   - CQS
#   - CQT
#   - CQV
#   - CRA
#   - CRB
#   - CRC
#   - CRD
#   - CRE
#   - CRG
#   - CRH
#   - CRI
#   - CRK
#   - CRL
#   - SACE_GAL
#   - SACE_GAP
#   - SACE_GAS
#   - SACE_GAT
#   - SACE_GAV
#   - SACE_MAA
#   - SACE_MAB
#   - SACE_MAL
#   - SACE_YAA
#   - SACE_YAB
#   - SACE_YAC
#   - SACE_YAD
#   - SACE_YAE
#   - SACE_YAF
#   - SACE_YAG
#   - SACE_YAK
#   - SACE_YAL
#   - SACE_YAM
#   - SACE_YAN
#   - SACE_YAP
#   - SACE_YAQ
#   - SACE_YAR
#   - SACE_YAT
#   - SACE_YAU
#   - SACE_YAV
#   - SACE_YAW
#   - SACE_YAX
#   - SACE_YAY
#   - SACE_YAZ
#   - SACE_YBA
#   - SACE_YBB
#   - SACE_YBE
#   - SACE_YBF
#   - SACE_YBG
#   - SACE_YBH
#   - SACE_YBJ
#   - SACE_YBK
#   - SACE_YBL
#   - SACE_YBM
#   - SACE_YBN
#   - SACE_YBO
#   - SACE_YBP
#   - SACE_YBQ
#   - SACE_YBR
#   - SACE_YBS
#   - SACE_YBT
#   - SACE_YBU
#   - SACE_YBV
#   - SACE_YBW
#   - SACE_YBX
#   - SACE_YBY
#   - SACE_YBZ
#   - SACE_YCA
#   - SACE_YCB
#   - SACE_YCC
#   - SACE_YCD
#   - SACE_YCE
#   - SACE_YCF
#   - SACE_YCG
#   - SACE_YCH
#   - SACE_YCI
#   - SACE_YCJ
#   - SACE_YCK
#   - SACE_YCL
#   - SACE_YCM
#   - SACE_YCN
#   - SACE_YCO
#   - SACE_YCP
#   - SACE_YCQ
#   - SACE_YCR
#   - SACE_YCS
#   - SACE_YCT
#   - SACE_YCU
#   - SACE_YCV
#   - SACE_YCW
#   - SACE_YCX
#   - SACE_YCY
#   - SACE_YCZ
#   - SACE_YDA
#   - SACE_YDB
#   - SACE_YDC
#   - SACE_YDD
#   - SACE_YDE
#   - SACE_YDF
#   - SACE_YDG
#   - SACE_YDH
#   - SACE_YDI
#   - SACE_YDJ
#   - SACE_YDK
#   - SACE_YDL
#   - SACE_YDM
#   - SACE_YDN
#   - SACE_YDO